#:schema node_modules/wrangler/config-schema.json
# wrangler.toml (wrangler v3.79.0^)


name = "sublink-worker"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "1234" }
]



[observability]
enabled = true
head_sampling_rate = 1
